class BACKPACK;
UNIT_BACKPACKS(BACKPACK,SUBCOMPONENT)

#ifdef BACKPACK_HEAVY
	class BACKPACK_HEAVY;
	UNIT_BACKPACKS(BACKPACK_HEAVY,SUBCOMPONENT)
#else
    #define BACKPACK_HEAVY BACKPACK
#endif

#ifdef BACKPACK_MEDIC
	class BACKPACK_MEDIC;
	UNIT_BACKPACKS(BACKPACK_MEDIC,SUBCOMPONENT)
#else
    #define BACKPACK_MEDIC BACKPACK
#endif

#ifdef BACKPACK_JTAC
	class BACKPACK_JTAC;
	UNIT_BACKPACKS(BACKPACK_JTAC,SUBCOMPONENT)
#else
    #define BACKPACK_JTAC BACKPACK
#endif