#define MAJOR 1
#define MINOR 0
#define PATCH 0
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCH.BUILD
#define VERSION_STR "" VERSION ""
#define VERSION_ARMA VERSION_STR
#define VERSION_ARMA_NUM MAJOR,MINOR,PATCH,BUILD
#define VERSION_CODENAME "Initial Release"
#define VERSION_TAG "v" VERSION_STR " - " VERSION_CODENAME
#define VERSION_TAG_SHORT "v" VERSION_STR
#define VERSION_TAG_NUM MAJOR,MINOR,PATCH,BUILD
#define VERSION_DATE "2024-06-27"
#define VERSION_TIME "12:00:00"
#define VERSION_TIMESTAMP VERSION_DATE " " VERSION_TIME
#define VERSION_YEAR "2024"
#define VERSION_AUTHOR "Salmon"
#define VERSION_AUTHOR_SHORT "Salmon"
#define VERSION_AUTHOR_TAG "@" VERSION_AUTHOR_SHORT
