#define COMPONENT medical_equipment
#define COMPONENT_BEAUTIFIED Medical Equipment

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_MEDICAL_EQUIPMENT
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_MEDICAL_EQUIPMENT
    #define DEBUG_SETTINGS DEBUG_SETTINGS_MEDICAL_EQUIPMENT
#endif

#include "script_macros.hpp"
