class OPTRE_Ins_URF_Soldier_Base;
class 73_OCLFBase: OPTRE_Ins_URF_Soldier_Base
{
    faction = "73_OCLF";
    author="73rd S-4 Team";
    editorSubcategory = "73_Infantry_EdSubCat";
    uniformClass="73_OCLF_Uniform";
    model="\OPTRE_FC_Units\Marines\h3_uniform.p3d";
    hiddenSelections[]=
    {
        "camo1"
    };
    hiddenSelectionsTextures[]=
    {
        "73_innie\OCLF\data\OCLF_uniform_CO.paa"
    };
    weapons[]=
    {
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "Throw",
        "Put"
    };
    Items[]=
    {
        "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light"
    };
    RespawnItems[]=
    {
        "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light"
    };
    magazines[]={
    };
    respawnMagazines[]={
    };
    linkedItems[]=
    {
        "73_M52B_Armor_Vest",
        "73_CH255_Helmet_Visor",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    respawnLinkedItems[]=
    {
        "73_M52B_Armor_Vest",
        "73_CH255_Helmet_Visor",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    class HitPoints: HitPoints
    {
        class HitFace: HitFace
        {
        };
        class HitNeck: HitNeck
        {
            armor=3;
        };
        class HitHead: HitHead
        {
        };
        class HitPelvis: HitPelvis
        {
            armor=3;
        };
        class HitAbdomen: HitAbdomen
        {
            armor=3;
        };
        class HitDiaphragm: HitDiaphragm
        {
            armor=3;
        };
        class HitChest: HitChest
        {
            armor=3;
        };
        class HitBody: HitBody
        {
        };
        class HitArms: HitArms
        {
            armor=3;
        };
        class HitHands: HitHands
        {
            armor=3;
        };
        class HitLegs: HitLegs
        {
            armor=3;
        };
    };
};
class 73_OCLF_Soldier_Rifleman: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Rifleman";
    weapons[]=
    {
        "73_MA37B",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_MA37B",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Medic: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Medic";
    attendant = 1;
    weapons[]=
    {
        "73_M6DS_Carbine_Foregrip",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_M6DS_Carbine_Foregrip",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke"
    };
    respawnMagazines[]=
    {
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "73_26Rnd_127x40_Mag_Black_Tracer",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke"
    };
    Items[]=
    {
     "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light", "73_Morphine", "73_Adrenaline", "73_PolyHemoglobinIV_1000"
    };
    RespawnItems[]=
    {
     "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light", "73_Morphine", "73_Adrenaline", "73_PolyHemoglobinIV_1000"
    };
};
class 73_OCLF_Soldier_Rifleman_AA: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Rifleman [AA]";
    backpack = "OPTRE_UNSC_Backpack";
    weapons[]=
    {
        "73_MA37B",
        "optre_M41_SSR",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_MA37B",
        "optre_M41_SSR",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "optre_m41_twin_heat_g_aa",
        "optre_m41_twin_heat_g_aa",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "optre_m41_twin_heat_g_aa",
        "optre_m41_twin_heat_g_aa",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Rifleman_AT: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Rifleman [AT]";
    backpack = "OPTRE_UNSC_Backpack";
    weapons[]=
    {
        "73_MA37B",
        "optre_M41_SSR",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_MA37B",
        "optre_M41_SSR",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "optre_m41_twin_heat",
        "optre_m41_twin_heat",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "optre_m41_twin_heat",
        "optre_m41_twin_heat",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_AutoRifleman: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="AutoRifleman";
    weapons[]=
    {
        "73_M247",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_M247",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "73_100Rnd_M247_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Breacher: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Breacher";
    weapons[]=
    {
        "73_M45TAC",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_M45TAC",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "73_6Rnd_8Gauge_Slugs",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Grenadier: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Grenadier";
    weapons[]=
    {
        "73_MA37BGL",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_MA37BGL",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "3Rnd_HE_Grenade_shell",
        "3Rnd_HE_Grenade_shell",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "3Rnd_HE_Grenade_shell",
        "3Rnd_HE_Grenade_shell",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Radioman: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Radioman";
    backpack = "";
    weapons[]=
    {
        "73_BR55HBM1_DMR",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_BR55HBM1_DMR",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "73_95x40_36Rnd_T_R",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Sniper: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Sniper";
    weapons[]=
    {
        "73_SRS99AM",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_SRS99AM",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "73_M232_145x114x4_APFSDS",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_SquadLead: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Squad Leader";
    weapons[]=
    {
        "73_MA37K",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_MA37K",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "73_32Rnd_762x51_Mag_Tracer_Yellow",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Soldier_Scout: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Scout";
    weapons[]=
    {
        "73_M392_DMR",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_M392_DMR",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "73_15Rnd_10x40_Mag",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};
class 73_OCLF_Officer: 73_OCLFBase
{
    scope=2;
    scopeCurator=2;
    displayName="Officer";
    weapons[]=
    {
        "",
        "73_MK50_Sidekick",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "",
        "73_MK50_Sidekick",
        "Throw",
        "Put"
    };
    linkedItems[]=
    {
        "73_M52B_Armor_Vest",
        "TCP_H_Beret_Red",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    respawnLinkedItems[]=
    {
        "73_M52B_Armor_Vest",
        "TCP_H_Beret_Red",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    magazines[]=
    {
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "73_12Rnd_10x31_SAP_Mag_Tracer",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};








class EventHandlers;
///////Heavy Forces///////////////
class 73_OCLFSpecOpsBase: 73_OCLFBase
{
    faction = "73_OCLF";
    author="73rd S-4 Team";
    editorSubcategory = "73_SpecOps_EdSubCat";
    uniformClass="73_OCLF_Uniform_Blk";
    model="\OPTRE_FC_Units\Marines\h3_uniform.p3d";
    hiddenSelections[]=
    {
        "camo1"
    };
    hiddenSelectionsTextures[]=
    {
        "73_innie\OCLF\data\OCLF_uniform_blk_CO.paa"
    };
    weapons[]=
    {
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "Throw",
        "Put"
    };
    Items[]=
    {
        "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light"
    };
    RespawnItems[]=
    {
        "73_Biofoam_Light","73_Biofoam_Light","73_Biofoam_Light"
    };
    magazines[]={
    };
    respawnMagazines[]={
    };
    linkedItems[]=
    {
        "73_M52B_Armor_Lancer",
        "73_CH255_Helmet_Lancer",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    respawnLinkedItems[]=
    {
        "73_M52B_Armor_Lancer",
        "73_CH255_Helmet_Lancer",
        "ItemMap",
        "ItemCompass",
        "ItemWatch",
        "ItemRadio",
        "OPTRE_NVG"
    };
    class HitPoints: HitPoints
    {
        class HitFace: HitFace
        {
        };
        class HitNeck: HitNeck
        {
            armor=5;
        };
        class HitHead: HitHead
        {
        };
        class HitPelvis: HitPelvis
        {
            armor=5;
        };
        class HitAbdomen: HitAbdomen
        {
            armor=5;
        };
        class HitDiaphragm: HitDiaphragm
        {
            armor=5;
        };
        class HitChest: HitChest
        {
            armor=5;
        };
        class HitBody: HitBody
        {
        };
        class HitArms: HitArms
        {
            armor=5;
        };
        class HitHands: HitHands
        {
            armor=5;
        };
        class HitLegs: HitLegs
        {
            armor=5;
        };
    };
};
class 73_OCLF_SpecOps_Rifleman: 73_OCLFSpecOpsBase
{
    scope=2;
    scopeCurator=2;
    displayName="Lancer Rifleman";
    weapons[]=
    {
        "73_M7_SMG",
        "Throw",
        "Put"
    };
    respawnWeapons[]=
    {
        "73_M7_SMG",
        "Throw",
        "Put"
    };
    magazines[]=
    {
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
    respawnMagazines[]=
    {
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "73_48Rnd_5x23Caseless_FMJ_Mag",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "OPTRE_M2_Smoke",
        "MA_M9_Frag_Mag"
    };
};