name = "73rd STB Mod V2"
author = "73rd S-4 Team"
prefix = "73STB"
mainprefix = "z"

include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE",
    "logo_co.paa",
]

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3
]
presets = [
    "Test"
]
parameters = [
    "-world=empty",
    "-noSplash",
    "-showScriptErrors",
    "-debug"
]
executable = "arma3profiling_x64"
mission = "73rdTesting.flat_green_terrain"

[version]
path = "addons/main/script_version.hpp"